# Generated by Django 4.0 on 2023-11-16 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.IntegerField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=255)),
                ('seating_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TravelDetail',
            fields=[
                ('travel_detail_id', models.IntegerField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_booking.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_booking.customer')),
                ('travel_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_booking.traveldetail')),
            ],
        ),
    ]
