# Generated by Django 4.0 on 2023-11-16 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0002_alter_bus_bus_id_alter_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='travel_detail',
            new_name='travel_detail_id',
        ),
        migrations.RenameField(
            model_name='traveldetail',
            old_name='bus',
            new_name='bus_id',
        ),
    ]
